### PR TITLE
Add links to community resources

### PR DESCRIPTION
**Pull request by nrb**
## What does this PR do / why we need it

The community mailing list and calendar were a little hard to find, so I added them to the community page.

## Which issue(s) does this PR fix

n/a

## PR acceptance criteria

- ~~Unit Tests~~
- ~~E2E Tests~~
- [x] Documentation

## How to test changes / Special notes to the reviewer

I checked all these links locally via `pnpm run dev` as well as `pnpm run lint`; hopefully no failures on those is enough.

### CODE REVIEW

**Review by tumido — APPROVED** [review]
/lgtm
/approve

**Review by tumido — APPROVED** [review]

**Comment by serenamarie125** [comment]
Thanks for the contribution!  We're in the midst of getting a new design for the entire site, but glad to get this up for the community 🎉

**Comment by tumido** [comment]
@serenamarie125 can you please approve via a review? GitHub is hard on me. First it required me to review. That was fine. Than it required me to rebase it and then it won't allow me to merge or accept my review because I've rebased it and therefore I've co-authored a commit here... Sigh...

**Review by serenamarie125 — APPROVED** [review]
lgtm

**Comment by serenamarie125** [comment]
Thanks @nrb @tumido just merged as well!

**Pull request merged**
