### PR TITLE
Allow the plugin button text to wrap

### PR DESCRIPTION
**Pull request by AayushSaini101**
## Resolving issue number  128 

* Allow the plugin button text to **wrap**

### CODE REVIEW

**Review by schultzp2020 — CHANGES_REQUESTED** [review]
Please use tailwindcss for all css styling. https://tailwindcss.com/

**Comment by schultzp2020** [comment]
@AayushSaini101 any updates?

**Comment by AayushSaini101** [comment]
Sorry @schultzp2020 for being late. Working on it

**Comment by Zaperex** [comment]
@AayushSaini101 can you run `prettier --fix`?

**Comment by schultzp2020** [comment]
@AayushSaini101 https://github.com/janus-idp/janus-idp.github.io/pull/131#issuecomment-1681121078

**Comment by Zaperex** [comment]
Closing in favor of #222

**Pull request closed without merging**
